import { usePageMeta } from '../hooks/usePageMeta'

const h2 = 'mt-8 text-lg font-semibold text-ink'
const p = 'mt-2 text-sm leading-relaxed text-ink-soft'
const ul = 'mt-2 list-disc space-y-1.5 pl-5 text-sm leading-relaxed text-ink-soft'

export default function Terms() {
  usePageMeta('Terms of Service — Telonote')

  return (
    <div className="mx-auto max-w-3xl px-6 py-12 sm:px-6">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">Terms of Service</h1>
      <p className="mt-2 text-sm text-ink-soft">Last updated: August 23, 2026</p>

      <p className={p}>
        These Terms of Service ("Terms") govern your access to and use of Telonote (the "Service"), available at
        telonote.com. By creating an account or using the Service, you agree to these Terms. If you don't agree,
        don't use the Service.
      </p>

      <h2 className={h2}>1. The Service</h2>
      <p className={p}>
        Telonote is a voice-note transcription service. It records audio you submit, transcribes it, and uses a
        personal vocabulary you build up over time ("context") to improve transcription accuracy for names, jargon,
        and terms specific to you.
      </p>

      <h2 className={h2}>2. Accounts</h2>
      <p className={p}>
        You must provide accurate information when creating an account and keep your login credentials secure.
        You're responsible for all activity that happens under your account. Tell us right away if you suspect
        unauthorized access.
      </p>

      <h2 className={h2}>3. Plans and Billing</h2>
      <p className={p}>
        Telonote offers a free plan with a limited daily audio-submission allowance, and a paid plan currently
        advertised at <strong className="text-ink">$7.89 USD/month</strong> for up to{' '}
        <strong className="text-ink">100MB of audio submitted per day</strong> (this includes audio you send for
        re-transcription, which counts the same as a new submission). Advertised pricing is subject to change at any
        time before you subscribe. <strong className="text-ink">The price and plan terms shown to you at checkout</strong>{' '}
        at the moment you subscribe are the authoritative terms that govern your subscription, regardless of what's
        listed elsewhere on the site.
      </p>
      <p className={p}>
        Paid subscriptions renew automatically each billing period until cancelled. Payments are processed by
        Paddle.com Market Ltd ("Paddle"), acting as our authorized reseller and merchant of record — your purchase
        is also subject to{' '}
        <a href="https://www.paddle.com" target="_blank" rel="noreferrer" className="text-brand-600 underline">
          Paddle's own buyer terms
        </a>
        . Because Paddle is the merchant of record, your payment method statement will show a charge from Paddle,
        not Telonote directly.
      </p>
      <p className={p}>
        You can cancel your subscription at any time from your account settings. Cancelling stops future renewals;
        see our <a href="/refunds" className="text-brand-600 underline">Refund Policy</a> for what happens to the
        current billing period.
      </p>

      <h2 className={h2}>4. Acceptable Use</h2>
      <ul className={ul}>
        <li>Don't use the Service for anything illegal, or to record anyone without the consent required by law in your jurisdiction.</li>
        <li>Don't attempt to disrupt, overload, reverse-engineer, or gain unauthorized access to the Service.</li>
        <li>Don't use the Service to process content that infringes someone else's rights.</li>
      </ul>
      <p className={p}>
        We may suspend or terminate accounts that violate these Terms, misuse the Service, or abuse our systems
        (including automated abuse of usage limits).
      </p>

      <h2 className={h2}>5. Your Content</h2>
      <p className={p}>
        You retain ownership of the audio, transcripts, and context vocabulary you submit ("Your Content"). You
        grant Telonote a limited license to store, process, and transcribe Your Content solely to provide and
        improve the Service for you. We don't claim ownership of Your Content, and we don't use it to train models
        for anyone other than you.
      </p>

      <h2 className={h2}>6. Service Availability</h2>
      <p className={p}>
        The Service is provided "as is" and "as available." We don't guarantee uninterrupted or error-free
        operation, and we may modify, suspend, or discontinue features (with reasonable notice where practical).
        Transcription is generated by automated systems and may contain errors — don't rely on it for anything
        where accuracy is critical without reviewing it yourself.
      </p>

      <h2 className={h2}>7. Disclaimers and Limitation of Liability</h2>
      <p className={p}>
        To the fullest extent permitted by law, Telonote is provided without warranties of any kind, express or
        implied. We are not liable for indirect, incidental, or consequential damages arising from your use of the
        Service. Our total liability for any claim relating to the Service is limited to the amount you paid us in
        the 12 months before the claim arose.
      </p>

      <h2 className={h2}>8. Changes to These Terms</h2>
      <p className={p}>
        We may update these Terms from time to time. If we make material changes, we'll take reasonable steps to
        let you know (such as an in-app notice or email). Continuing to use the Service after changes take effect
        means you accept the updated Terms.
      </p>

      <h2 className={h2}>9. Governing Law</h2>
      <p className={p}>
        These Terms are governed by the laws applicable in our principal place of business, without regard to
        conflict-of-law principles.{' '}
        <em>[Telonote: fill in your actual state/country of incorporation or residence here.]</em>
      </p>

      <h2 className={h2}>10. Contact</h2>
      <p className={p}>
        Questions about these Terms? Email{' '}
        <a href="mailto:support@telonote.com" className="text-brand-600 underline">
          support@telonote.com
        </a>
        .
      </p>
    </div>
  )
}
